mvp-01
yurchenkosv/gofermart pull request #1
Opened 2022-08-07 21:39 UTC by yurchenkosv

2022-08-16 16:55 UTC, sergeysergeevru requested changes
Привет) Очень порадовало наличие мок тестов, структура тоже хорошая. Из того что хочется в первую очередь поправить это работа с базой (транзакции, переиспользование коннекта), проверка ошибок. Спасибо!)

2022-08-16 16:55 UTC, sergeysergeevru commented on cmd/gophermart/migrate.go
> +	if err := m.Up(); err != nil && err != migrate.ErrNoChange {
предпочитаю ошибки сравнивать через error.Is, на случай если ошибка была обернута

2022-08-16 16:55 UTC, sergeysergeevru commented on internal/config/serverConfig.go
> +	Repo                 *dao.PostgresRepository
это к конфигурации приложения не относится по своей природе

2022-08-16 16:55 UTC, sergeysergeevru commented on internal/controllers/accrualController.go
> +	}
имеет смысл унести в отдельный криент, чтобы вся логика крывалась за каким нибудь интерфейсом наподобие
```go
type AccrualProvider interface {
     GetByID(orderID string) (*dto.AccrualStatus, error)
}
```
тогда имплементации можно подменять и мокать если понадобится

2022-08-16 16:55 UTC, sergeysergeevru commented on cmd/gophermart/main.go
> +	token, err := generateRandomToken()
получается при каждом перезапуске приложения старые сессии будут невалидны. А при горизонтальном масштабировании, если балансировщик не будет делать никакой магии, сессии будут работать через раз.

2022-08-16 16:55 UTC, sergeysergeevru commented on internal/dao/postgresRepository.go
> +}
в общем и целом не очень понятно преимущество выносить все в отдельную функцию getWithdrawalsForCurrentUser, а не сразу разместить в данном методе. Далее аналогично)

2022-08-16 16:55 UTC, sergeysergeevru commented on internal/dao/postgresRepository.go
> +}
беды в этом нет, но тем не менее и преимуществ не могу придумать

2022-08-16 16:55 UTC, sergeysergeevru commented on internal/dao/postgresRepository.go
> +}
лучше явно иметь отдельный метод под каждую модель, чем такой универсальный. если попытаемся сохранить неподдерживаемую модель, то компилятор это не отловит и обнаружим эту проблему только при работе приложения.

2022-08-16 16:55 UTC, sergeysergeevru commented on internal/dao/postgresRepository.go
> +	conn, err := sqlx.Connect("postgres", connect)
создание коннекта к базе дорогая операция, если так делать на каждый запрос, то ручки будут отрабатывать гораздо дольше. Плюс при обработке большого числа реквестов может получиться что мы откроем  больше коннектов к базе, чем поддерживает база. Собственно коннект надо создавать один раз и переиспользовать.

2022-08-16 16:55 UTC, sergeysergeevru commented on internal/dao/postgresRepository.go
> +		log.Fatalf("Unable to connect to database: %v\n", err)
фатал сделает os.Exit(1) и завершит приложение. Лучше ошибку выше возвращать.

2022-08-16 16:55 UTC, sergeysergeevru commented on internal/dao/postgresRepository.go
> +	conn, err := sqlx.Connect("postgres", connect)
далее аналогично

2022-08-16 16:55 UTC, sergeysergeevru commented on internal/dao/postgresRepository.go
> +	_ = rows.Err()
https://github.com/golang/go/wiki/CodeReviewComments#handle-errors

2022-08-16 16:55 UTC, sergeysergeevru commented on internal/dao/postgresRepository.go
> +		result.Scan(
скан возвращает ошибку, если что-то пошло не так, поэтому ошибку стоит проверять иначе есть риск продолжить работу с неконсистентными данными

2022-08-16 16:55 UTC, sergeysergeevru commented on internal/dao/postgresRepository.go
> +		result.Scan(
далее аналогично

2022-08-16 16:55 UTC, sergeysergeevru commented on internal/dao/postgresRepository.go
> +}
по факту это GetBalanceByID, я бы предложил дергать баланс по конкретному полю, без прокидывания всей модели. Иначе непонятно как этот метод работает, когда читаешь код

2022-08-16 16:55 UTC, sergeysergeevru commented on internal/dao/postgresRepository.go
> +}
могу придраться аналогично предыдущему

2022-08-16 16:55 UTC, sergeysergeevru commented on internal/dao/postgresRepository.go
> +}
непонятно какие withdrawals вытаскиваются из базы, логичнее сделать GetWithdrawalsByUserID(userId int)

2022-08-16 16:55 UTC, sergeysergeevru commented on internal/errors/user.go
> +}
когда сама структура ошибки никакой информации не несет можно просто создавать глобальную ошибку:
```go
var InvalidUserError = fmt.Errorf("invalid username or password")
```
дальше можно будет чекать ошибку через errors.Is(err, InvalidUserError)

2022-08-16 16:55 UTC, sergeysergeevru commented on internal/handlers/auth.go
> +	auth := service.NewAuthService(cfg.Repo)
«Я уже говорил тебе, что такое безумие? Безумие — это точное повторение одного и того же действия раз за разом в надежде на изменение. Это. Есть. Безумие» Чего-то вспомнилось. Собственно конечно в этом ничего смертельного нет, но тебе приходится в каждом хендлере делать однотипные вещи, которые достаточно сделать один раз. Для этого можно просто все хендлеры сделать методами структуры и инкапсулировать туда все что нужно.
Допустим примерно так
```go
type Handler struct {
    authService *service.Auth
}

func NewHandler(authService *service.Auth) Handler {
    return Handler{authService: authService}
}

func (h Handler) HandleUserRegistration(writer http.ResponseWriter, request *http.Request) {
	//тут парсим информацию из рекверста
        // а потом вызываем бизнес логику 
        h.authService.RegisterUser(&user)
        //  ну а дальше вполне ок вроде
}
```
в принципе дальше я думаю разберешься)

2022-08-16 16:55 UTC, sergeysergeevru commented on internal/handlers/auth.go
> +	CheckErrors(err, writer)
ок под капотом ты залогируешь ошибку, но при этом алгоритм не завершается и идет дальше. ИМХО если вылетела ошибка то здесь мы уже можем закончить

2022-08-16 16:55 UTC, sergeysergeevru commented on internal/handlers/auth.go
> +	CheckErrors(err, writer)
по факту проблема во всех местах употребления этой функции

2022-08-16 16:55 UTC, sergeysergeevru commented on internal/handlers/balance.go
> +	body, _ := json.Marshal(balance)
проверка ошибки

2022-08-16 16:55 UTC, sergeysergeevru commented on internal/handlers/balance.go
> +	balanceService := service.NewBalance(cfg.Repo)
аналогичная проблематика как и с использование Auth

2022-08-16 16:55 UTC, sergeysergeevru commented on internal/handlers/balance.go
> +	body, _ := io.ReadAll(request.Body)
проверка ошибки

2022-08-16 16:55 UTC, sergeysergeevru commented on internal/handlers/balance.go
> +	body, _ := json.Marshal(withdrawals)
проверка ошибки

2022-08-16 16:55 UTC, sergeysergeevru commented on internal/handlers/orders.go
> +	order.UploadTime = now
nit: с точки зрения читаемости удобнее так:
```go
	userID := GetUserIDFromToken(request.Context())
        order := model.Order {
              Number: orderNum,
              Status: model.OrderStatusNew,
              User: &model.User{ID: &userID},
              UploadTime: time.Now(),
       }
```

2022-08-16 16:55 UTC, sergeysergeevru commented on internal/middlewares/context.go
> +			ctx = context.WithValue(ctx, model.ConfigKey("config"), config)
контекст однозначно не подходит для передачи конфига. Если он где-то нужен, стоит передавать явно или инкапсулируя в структуры нужных слоев

2022-08-16 16:55 UTC, sergeysergeevru commented on internal/service/auth.go
> +	savedUser, _ := auth.repo.GetUser(user)
если здесь вылетает ошибка из чего следует что savedUser == nil, то на строчку ниже будет выброшена паника, правда конечно это произойдет, если nil будет прокинут сверху. В любом случае ошибки стоит проверять

2022-08-16 16:55 UTC, sergeysergeevru commented on internal/service/balance.go
> +func NewBalance(repo dao.Repository) Balance {
не вижу смысла возвращать здесь интерфейс, это же конструктор, а не фабрика. https://bryanftan.medium.com/accept-interfaces-return-structs-in-go-d4cab29a301b

2022-08-16 16:55 UTC, sergeysergeevru commented on internal/service/balance.go
> +func NewBalance(repo dao.Repository) Balance {
вот если бы выглядело так 
```go
type BalanceProvider interface {
	GetBalanceByID(userId int) (*model.Balance, error)
}

type BalanceService struct {
	repo BalanceProvider
}
func NewBalanceService(repo BalanceProvider) BalanceService {
        return BalanceService{repo: repo}
}

func (b BalanceService) GetCurrentUserBalance(userID int) (*model.Balance, error) {
	return b.repo.GetBalanceByID(userID)
}
```
Вот такой подход приносит больше гибкости: так как мы используем только один метод репо, то только его и требуем от приходящей структуры. При этом если у нас появится новый метод для сервиса, то вернув структуру из конструктора мы сразу же имеем доступ к этому методу и нам не придется еще ходить и менять интерфейс.

2022-08-16 16:55 UTC, sergeysergeevru commented on internal/service/order.go
> +	orderNum, _ := strconv.Atoi(order.Number)
тут очень опасно: если мы требуем чтобы заказ был однозначно в виде числа, то в случае ошибки дальше будет оперировать orderNum = 0

2022-08-16 16:55 UTC, sergeysergeevru commented on internal/service/order.go
> +	defer mux.Unlock()
мьютекс здесь обезопасит от состояния гонки, но любой параллельный процессинг превратит в последовательный. Можно просто выполнять всю логику в марках одной транзакции

2022-08-16 16:55 UTC, sergeysergeevru commented on internal/service/order.go
> +	defer mux.Unlock()
и если запустим несколько инстансов приложения, то мьютексы не дадут безопасности

2022-08-16 16:55 UTC, sergeysergeevru commented on internal/service/withdraw.go
> +	//TODO надо делать списание и обновление баланса в одной транзакции
я полностью согласен, рад что сам имеешь представление, тогда расписывать этот момент не буду)

2022-08-16 19:32 UTC, yurchenkosv commented on cmd/gophermart/main.go
> +	token, err := generateRandomToken()
Сначала сделал статический ключ, но как раз из за того, что он постоянно одинаковый показалось небезопасно. Наверное, стоит такое выносить в конфиг, чтобы при компрометации ключа можно было сделать новый без пересборки.

2022-08-16 20:14 UTC, yurchenkosv commented on internal/dao/postgresRepository.go
> +}
Была идея, что withdrawals можно просить не только для конкретного пользователя, но и по другим критериям, к примеру по номеру заказа. Этот метод задумывался как метод диспетчер, который в зависимости от наполнения полей структуры сможет понять какую функцию дернуть. Впрочем, сейчас смотрю на эту идею и выглядит как то ненадежно. Наверное, лучше явное поведение.

2022-08-16 20:17 UTC, yurchenkosv commented on internal/errors/user.go
> +}
Так по идее однообразней, да, сейчас не несет информации, а потом захотим полей накидать, тогда ничего не надо будет переписывать, только изменить метод Error()

2022-08-16 20:19 UTC, yurchenkosv commented on internal/dao/postgresRepository.go
> +		log.Fatalf("Unable to connect to database: %v\n", err)
Это явный косяк, не понимаю как пропустил. (
Будет очень неожиданно завершать приложение тут

2022-08-17 16:04 UTC, yurchenkosv commented on internal/handlers/auth.go
> +	CheckErrors(err, writer)
Тут почему то думал, что WriteHeader пишет хедер и завершает обработку хендлера. Но он не завершает. Спасибо, что подсветил

2022-08-19 16:54 UTC, sergeysergeevru approved these changes
Привет. Проблема со списанием к сожалению осталась. Постарался описать ее суть, надеюсь понятно будет, если нет, то напиши. По тестам тоже описал свое мнение, но в любом случае получилось интересно и время потрачено не зря. Собственно думаю с транзакцией разберешься уже в своем темпе, поэтому принимаю работу. Спасибо!

2022-08-19 16:54 UTC, sergeysergeevru commented on internal/service/withdraw.go
> +		err = s.repo.SaveBalance(&b)
ты твой `r` из аргумента не используешь. Тогда должно быть так
```suggestion
		err = r.SaveBalance(&b)
```
ниже аналогично

2022-08-19 16:54 UTC, sergeysergeevru commented on internal/dao/postgresRepository_test.go
> +		})
нет тест кейсов) В итоге мы даже ничего не проверили, но время время потрачено на них. Собственно может ты авгонеренацией воспользовался, тогда не так страшно

2022-08-19 16:54 UTC, sergeysergeevru commented on internal/dao/postgresRepository_test.go
> +package dao
В общем по тестам в файле: если смотреть со стороны академической -  однозначно интересно. Для реального бизнесового приложения, не сказал бы, что покрытие тестами репозитори слишком значимо. В первую очередь я бы уделил внимание api и бизнес логике, так как это наиболее критичные части, а обертки вокруг базы данных обычно довольно прямолинейные и там меньше шансов допустить ошибку. Вполне возможно кто-то со мной не согласится, вопрос может быть дискуссионным. Но вообще большой плюс что потрогал такой подход и попробовал)

2022-08-19 16:54 UTC, sergeysergeevru commented on cmd/gophermart/main.go
> +	os.Exit(0)
у тебя дальше ничего нет, поэтому в любом случае приложение успешно завершится)

2022-08-19 16:54 UTC, sergeysergeevru commented on internal/service/withdraw.go
> +	err = s.repo.Atomic(ctx, func(r dao.Repository) error {
фактически, этот кусок начиная с GetBalanceByUserID должен тоже уйти под транзакцию: если будут выполняться два запроса параллельно и оба дернут GetBalanceByUserID до обновления баланса, то если одна из транзакций закончится до начала транзакции в другом параллельном запросе у нас обе транзакции завершатся успешно.

2022-08-22 16:25 UTC, yurchenkosv commented on internal/dao/postgresRepository_test.go
> +		})
Да, тут не хватило времени на покрытие всего тестами. Действительно использовал автогенерацию

2022-08-22 16:27 UTC, yurchenkosv commented on internal/dao/postgresRepository_test.go
> +package dao
Согласен тут. К примеру, тестов api нету, но планируются.
Интересно было пощупать testcontainers. Применяются часто, но злоупотреблять не стоит. Видел проекты где вынесли все в интеграционные тесты с testcontainers и потом очень страдали из-за медлительности тестов

2022-08-22 16:27 UTC, yurchenkosv commented on cmd/gophermart/main.go
> +	os.Exit(0)
Решил тут не оставить шансов )

2022-08-22 16:28 UTC, yurchenkosv commented on internal/service/withdraw.go
> +	err = s.repo.Atomic(ctx, func(r dao.Repository) error {
Согласен тут, поступил невнимательно. Спасибо, поправлю.

2022-08-22 16:34 UTC, yurchenkosv commented on internal/service/withdraw.go
> +		err = s.repo.SaveBalance(&b)
Действительно. Тем самым я не использую транзакцию (
Спасибо, что подсветил

2022-10-02 09:21 UTC, merged